services:
  metabase:
    image: metabase/metabase:v0.53.x
    container_name: metabase
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    volumes:
      - ./metabase/metabase-data/:/metabase-data
    env_file:
      - ./metabase/metabase.env
    networks:
      - flight-analytics-net