services:
  spark-master:
    image: bde2020/spark-master:3.0.1-hadoop3.2
    container_name: spark-master
    ports:
      - 8000:8080
      - 7077:7077
    environment: 
      - PYSPARK_PYTHON=python3
    env_file:
      - ./spark/spark.env
    volumes:
      - ./spark/scripts:/home/scripts
    networks:
      - flight-analytics-net

  spark-worker-1:
    image: bde2020/spark-worker:3.0.1-hadoop3.2
    container_name: spark-worker-1
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - 8001:8081
    env_file:
      - ./spark/spark.env
    networks:
      - flight-analytics-net
  
  spark-worker-2:
    image: bde2020/spark-worker:3.0.1-hadoop3.2
    container_name: spark-worker-2
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - 8002:8081
    env_file:
      - ./spark/spark.env
    networks:
      - flight-analytics-net
