
services:
  nifi:
    image: apache/nifi:1.15.3
    container_name: nifi
    ports:
      - "8443:8443"
    volumes:
      - ./data/:/data/
      - ./nifi/hadoop/core-site.xml:/home/nifi/core-site.xml
      - nifi_conf:/opt/nifi/nifi-current/conf
      - nifi_database_repository:/opt/nifi/nifi-current/database_repository
      - nifi_flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - nifi_content_repository:/opt/nifi/nifi-current/content_repository
      - nifi_provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - nifi_state:/opt/nifi/nifi-current/state
    env_file:
      - ./nifi/nifi.env
    networks:
      - flight-analytics-net

  nifi-registry:
    image: apache/nifi-registry:1.15.3
    container_name: nifi-registry
    ports:
      - "18080:18080"
    volumes:
      - nifi_registry:/opt/nifi-registry/nifi-registry-current/
    networks:
      - flight-analytics-net

volumes:
  nifi_conf: {}
  nifi_database_repository: {}
  nifi_flowfile_repository: {}
  nifi_content_repository: {}
  nifi_provenance_repository: {}
  nifi_state: {}
  nifi_registry: {}
