services:
  zookeeper:
    image: zookeeper:3.8
    container_name: zookeeper
    restart: always
    env_file:
      - ./kafka/zookeeper.env
    ports:
      - "2181:2181"
    networks:
      - flight-analytics-net

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    env_file:
      - ./kafka/kafka.env
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - flight-analytics-net

volumes:
  kafka_data: