services:
  mongodb:
    image: mongo:8.2
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_storage:/data/db
    networks:
      - flight-analytics-net
  
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ./mongo/mongo.env
    depends_on:
      - mongodb
    networks:
      - flight-analytics-net

volumes:
  mongodb_storage: